export { default as AdaIcon } from './pastoraAda.jpg'
export { default as AxelIcon } from './axelIcon.png'
export { default as JulioIcon } from './julioIcon.png'
export { default as MariaIcon } from './mariaIcon.png'
export { default as MikeIcon } from './mikeIcon.png'
export { default as NeftaliIcon } from './neftaliIcon.png'
export { default as SilviaIcon } from './silviaIcon.png'
export { default as TabernaculoIcon } from './tabernaculoIcon.png'
export { default as YadiIcon } from './yadiIcon.png'

export { default as AdaSquare } from './adaSquare.png'
export { default as AxelSquare } from './axelSquare.png'
export { default as JulioSquare } from './julioSquare.png'
export { default as MikeSquare } from './mikeSquare.png'
export { default as YadySquare } from './yadySquare.png'
