export { default as Bg1 } from './bg1.png'
export { default as Bg2 } from './bg2.png'
export { default as Bg3 } from './bg3.png'
export { default as BgImg } from './locationBgImg.png'
export { default as PastorMikeBg } from './pastorMikeBgImg.png'
