export { default as Axel } from './axel.jpg'
export { default as Mike } from './mike.jpg'
export { default as Julio } from './julio.jpg'
export { default as Eating } from './sittingEating.jpg'
export { default as Beach } from './beach.jpg'
